### ISSUE TITLE
Collision appears to be detected too early.

### ISSUE THREAD

**Issue by rgordonathome** [rsgc-ics2o-fall2015/Dino_Dodge_Refactored#1]
Expected behaviour: Cactus is touching Dino to trigger a collision.

Actual behaviour: Game stops when the cactus appears to be separated from the Dino.

See image below.

![screen shot 2015-11-02 at 8 37 37 am](https://cloud.githubusercontent.com/assets/2380516/10882993/fcb5c344-813c-11e5-8f49-0db6d604589f.png)

**Comment by rgordonathome** [comment]
See attached image. 

![screen shot 2015-11-02 at 8 42 55 am](https://cloud.githubusercontent.com/assets/2380516/10883101/ba7b0d26-813d-11e5-924e-a85efae88c4e.png)

**Comment by rgordonatrsgc** [comment]
This issue is now fixed. See example below.

![screen shot 2015-11-02 at 9 04 01 am](https://cloud.githubusercontent.com/assets/2380516/10883617/24a7b926-8141-11e5-9c80-c86cbee07963.png)
